<%@ Page Title="" Language="C#" MasterPageFile="~/Admin_Pages/Admin.master" AutoEventWireup="true" CodeFile="Admin_News.aspx.cs" Inherits="Admin_Pages_Admin_News" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
<style type="text/css">
#table1 td:first-child
{
    width:130px;
    }
</style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
<!--News Div starts here-->
<h2 style="float:right;font-size:23px"><img src="../images/logobig3.png" /> News Details</h2>
<img src="../images/active.png" width="100%" height="3px" />
<br /><br />

<center>
<ul class="menu">
<li><a href="Admin_News.aspx?sh=view1" class="active" title="1" id="addnews" runat="server">Add</a></li>
			<li><a href="Admin_News.aspx?sh=view2" id="editnews" title="2" runat="server">Delete</a></li>
			</ul><!-- Menu end -->
        <br />
        <br />

        <asp:MultiView ID="MultiView1" runat="server" ActiveViewIndex="0">
        <asp:View ID="view1" runat="server">
<div id="div1" class="newsdiv" style="width:100%">
    <div id="did_you_know" style="height:inherit;width:700px;">
    <br /><table id="table1" style="text-align:left" cellpadding="5" runat="server">
            <tr><td>News HeadLine</td><td>:</td><td>
                <asp:TextBox ID="newshead" runat="server"></asp:TextBox><br />
                <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" ErrorMessage="Please enter a headline" ForeColor="Red" ControlToValidate="newshead" SetFocusOnError="true"></asp:RequiredFieldValidator> 
                </td></tr>
                <tr><td>News By - Name</td><td>:</td><td>
                <asp:TextBox ID="newsname" runat="server"></asp:TextBox><br />
                    <asp:RequiredFieldValidator ID="RequiredFieldValidator2" runat="server" ErrorMessage="Please enter a name" ControlToValidate="newsname" ForeColor="Red" SetFocusOnError="true" Display="Dynamic"></asp:RequiredFieldValidator>
                    <asp:RegularExpressionValidator ID="RegularExpressionValidator1" runat="server" ErrorMessage="Only aplhabets allowed" ForeColor="Red" Display="Dynamic" SetFocusOnError="true" ControlToValidate="newsname" ValidationExpression="^[\sa-zA-Z]*"></asp:RegularExpressionValidator>
                </td></tr>
                <tr><td>News By - Email</td><td>:</td><td>
                <asp:TextBox ID="newsemail" runat="server"></asp:TextBox><br />
                    <asp:RequiredFieldValidator ID="RequiredFieldValidator3" runat="server" ErrorMessage="Please enter a mail ID" ForeColor="Red" ControlToValidate="newsemail" Display="Dynamic" SetFocusOnError="true"></asp:RequiredFieldValidator>
                    <asp:RegularExpressionValidator ID="RegularExpressionValidator2" runat="server" ErrorMessage="Email-ID is in wrong format" ControlToValidate="newsemail" ForeColor="Red" SetFocusOnError="true" Display="Dynamic" ValidationExpression="\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*"></asp:RegularExpressionValidator>
                </td></tr>
            <tr><td>News Details</td><td>:</td><td>
                <textarea id="newsdetail" cols="80" rows="8" runat="server"></textarea><br />
                <asp:RequiredFieldValidator ID="RequiredFieldValidator4" runat="server" ErrorMessage="Please enter an description" ForeColor="Red" SetFocusOnError="true" ControlToValidate="newsdetail"></asp:RequiredFieldValidator>
                </td></tr>
            <tr><td>Attachment</td><td>:</td><td>
                <asp:FileUpload ID="newsattach" runat="server" /></td></tr>
            <tr><td></td><td></td><td></td></tr> 
            <tr><td></td><td></td><td> <asp:Label ID="success1" runat="server" Text="" ForeColor="GreenYellow"></asp:Label>
                </td>  </tr>
            </table>
            <br />
       
          <asp:Button ID="NewsAdd" CssClass="submitbutton" runat="server" Text="Add News" onclick="NewsAdd_Click" />      
     <br /><br />
    </div>
</div>
</asp:View>
<asp:View ID="view2" runat="server">
 <div id="div2" class="newsdiv" style="width:100%">
    <br /><br /><asp:GridView ID="NewsGridView1" runat="server" AllowPaging="True" DataKeyNames="rowid"
         CellPadding="5" HorizontalAlign="Center" ForeColor="#333333" GridLines="None" 
        onpageindexchanging="NewsGridView1_PageIndexChanging" AutoGenerateColumns="False" PageIndex="1" ShowFooter="True" 
        AutoGenerateDeleteButton="true" onrowdeleting="NewsGridView1_RowDeleting">
        <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
<RowStyle BackColor="#EFF3FB" />
<SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
<HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
<AlternatingRowStyle BackColor="White" /><PagerSettings PageButtonCount="5" />
        <PagerStyle BackColor="#FFCC66" ForeColor="#333333" HorizontalAlign="Right" />
        
    <Columns>
        <asp:BoundField DataField="rowid" HeaderText="Id" />
            <asp:BoundField DataField="newsid" HeaderText="NewsId" />
        <asp:BoundField DataField="headline" HeaderText="Headline" />
         <asp:BoundField DataField="name" HeaderText="News By" />
    
      
  </Columns>
  
       </asp:GridView>
     
</div>
</asp:View>
</asp:MultiView>
<!-- news div ends here-->
</center>
</asp:Content>

